# Generated by Django 6.1.1 on 2026-09-13 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Proveedor')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Unidad de Medida')),
                ('abreviatura', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='actualizado_el',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='almacen',
            name='ubicacion_fisica',
            field=models.CharField(default='Principal', max_length=200, verbose_name='Ubicación Física'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='TEMP-SKU', max_length=50, unique=True, verbose_name='SKU Único'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='almacen',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de Almacén'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor', verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='inventario.unidad', verbose_name='Unidad de Medida'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Zona')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen', verbose_name='Almacén')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código (Pasillo-Rack-Nivel)')),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad Máxima')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
    ]
